#!/usr/bin/env python

"""
Sample script for starting MVC3GaugeController vacuum gauge
"""

import os
import sys

SERVER_PATH = '/ds/python/VacuumController/MVC3GaugeController'


def main():
    tango_home = os.environ['TANGO_HOME']
    path =  tango_home + SERVER_PATH
    sys.path.insert(0,path)
    import MVC3GaugeController
    MVC3GaugeController.main(sys.argv)

if __name__ == '__main__':
    main()
